version: 0.0
os: linux
permissions:
  - object: /changescicd.sh
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: /changescicd.sh
      timeout: 40
      runas: ec2-user