version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rdscicd
permissions:
  - object: /home/ec2-user/rdscicd
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
hooks:
  BeforeInstall:
  AfterInstall:
    - location: /home/ec2-user/rdscicd
      timeout: 180