version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rdscicd
permissions:
  - object: /home/ec2-user/rdscicd
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/rdscicd
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: /dbcicd.sh
      timeout: 40
      runas: ec2-user